// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '#',
    appId: '1:535539726169:web:cbdb884434da22c76abe48',
    messagingSenderId: '535539726169',
    projectId: 'tiktok-travel-98dbb',
    authDomain: 'tiktok-travel-98dbb.firebaseapp.com',
    storageBucket: 'tiktok-travel-98dbb.appspot.com',
    measurementId: 'G-VX8RRPNP5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '#',
    appId: '1:894691517895:android:f6e0124eda65557f1725e2',
    messagingSenderId: '894691517895',
    projectId: 'tiktok-travel-a1e73',
    storageBucket: 'tiktok-travel-a1e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '#',
    appId: '1:894691517895:ios:5bdd1062565b2cf81725e2',
    messagingSenderId: '894691517895',
    projectId: 'tiktok-travel-a1e73',
    storageBucket: 'tiktok-travel-a1e73.appspot.com',
    iosBundleId: 'com.example.tiktokTravel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '#',
    appId: '1:535539726169:ios:70f0fc9834c0d1e16abe48',
    messagingSenderId: '535539726169',
    projectId: 'tiktok-travel-98dbb',
    storageBucket: 'tiktok-travel-98dbb.appspot.com',
    iosBundleId: 'com.example.tiktokTravel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '#',
    appId: '1:535539726169:web:3d1119751957f7e36abe48',
    messagingSenderId: '535539726169',
    projectId: 'tiktok-travel-98dbb',
    authDomain: 'tiktok-travel-98dbb.firebaseapp.com',
    storageBucket: 'tiktok-travel-98dbb.appspot.com',
    measurementId: 'G-YQS20S785Q',
  );
}